fp exercise done
orevenat/study pull request #2
Opened 2021-10-29 15:41 UTC by orevenat

В rating при суммировании расчет с ошибкой при суммировании дробных чисел через reduce (которой с использованием sum нет), это сделано намеренно?

2021-11-07 14:25 UTC, moklidia requested changes

2021-11-07 14:25 UTC, moklidia commented on test/exercise/fp/solution.rb
> +            new_acc
Давай в начале сделаем выборку нужных фильмов через select, а потом будем подсчитывать их рейтинг

2021-11-07 14:25 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        end
Фильтрация должна быть реализована через select. reduce используется для аггрегации.

2021-11-07 15:19 UTC, orevenat commented on test/exercise/fp/solution.rb
> +            new_acc
Спасибо. Смутило что написано, что написано было  ```Оба задания нужно решить используя map и reduce```

2021-11-09 06:38 UTC, moklidia approved these changes

2021-11-09 12:05 UTC, merged