fp2 exercise done
orevenat/study pull request #3
Opened 2021-11-05 12:51 UTC by orevenat

2021-11-07 14:27 UTC, moklidia requested changes

2021-11-07 14:27 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        end
Функциональное программирование не предполагает использование циклов. Попробуй реализовать через рекурсию.

2021-11-09 06:37 UTC, moklidia requested changes

2021-11-09 06:37 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        my_each do |x|
Что такое 'x'? Придумай понятное название для переменной.

2021-11-09 06:37 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +
Непонятно что такое `blk`

2021-11-10 08:12 UTC, NickelGit requested changes

2021-11-10 08:12 UTC, NickelGit commented on test/exercise/fp2/solution.rb
> +        end
деление массива можно реализовать более компактно через синтаксис
`head, *rest = array`
где в переменную `head` будет попадать первый элемент массива или `nil` в случае если массив пустой, а в `rest` будет попадать оставшаяся часть массива кроме первого элемента. Если в массиве будет один элемент или он будет пустым то в `rest` попадет пустой массив. 
Соответственно проверить есть ли еще необработанные элементы можно будет с помощью одного guard clause в самом начале.

2021-11-10 08:12 UTC, NickelGit commented on test/exercise/fp2/solution.rb
> +        self.my_each do |item|
`my_map` нужно реализовать через `my_reduce`

2021-11-10 08:12 UTC, NickelGit commented on test/exercise/fp2/solution.rb
> +        self.my_each do |item|
`my_compact` нужно реализовать через `my_reduce`

2021-11-10 08:12 UTC, NickelGit commented on test/exercise/fp2/solution.rb
> +        end
`my_reduce ` нужно реализовать используя рекурсию

2021-11-12 12:12 UTC, moklidia approved these changes

2021-11-12 13:22 UTC, merged